### PR TITLE
Some code adjustments

### PR DESCRIPTION
**Pull request by byNoobiYT**
typos, javadoc, variables, NPEs (null checks) etc. fixes and/or adds this pr. Please check the code before merging because everyone can make mistakes. (I haven't looked at all classes yet xd)

### CODE REVIEW

**Comment by mtorials** [comment]
Hey! One thing I noticed so far: In Music.java you changed the IDs to entities. The music object is needed as long as a bot is in the voice channel. We try to use IDs there instead of entities, beacuse you can not rely on the API to keep the entites (made an issue a while ago, do not know if it is still there....). For interfacing though we do use entities.
The second reason for using IDs. In Music I deal with multiple bots, multiple JDA instances, And an user you get from the JDA "Progen" is not the same as one you get from for example "Progen Music 1". Did you test it with multiple bots?

**Comment by mtorials** [comment]
Here it is:
https://github.com/DV8FromTheWorld/JDA/wiki/19)-Troubleshooting

**Comment by byNoobiYT** [comment]
I'm gonna revert this ASAP. I haven't noticed it... Sorry

**Comment by mtorials** [comment]
Thanks! I really appreciate your work. There is really some messed up stuff in our codebase...... If you are interested in new features instead of cleaning up, just open an issue or join our discord.

**Pull request merged**
