### PR TITLE
Custom owners. mutible music bots, logger

### LINKED ISSUE #26: Deactivate music bots
It should be possible to deactivate the music bots, when no token is provided.

### LINKED ISSUE #32: Add possibility to add/set bot owners in config

### PR DESCRIPTION
**Pull request by byNoobiYT**
## Requirements for Contributing

* [x] The changed and/or added Code should be documented and understandable.
* [x] The changed and/or added Code should follow the Code Conventions.

## Type of the Pull Request
* [x] Bugfix
* [x] Feature change
* [ ] Documentation change
* [x] Something different

## Description of the Changes

This PR adds custom owners, multiple music bots, logger and some optimization.

## References

Resolves #32 and resolves #26

## Dependencies

/

### CODE REVIEW

**Comment by byNoobiYT** [comment]
Multiple music tokens aren't tested yet. But it should work like the admin list.

**Comment by mtorials** [comment]
Sorry

**Comment by byNoobiYT** [comment]
It's also in #47 included

**Comment by mtorials** [comment]
Ok then I will close this one

**Pull request closed without merging**
