### PR TITLE
Adds the playlist command #81

### LINKED ISSUE #81: Playlist
Bugs:
- Playlist does not load
- pb!music start must execute

New Changes:
- playlist add/remove *playlistname* <song/url>
  - add or remove songs from your playlist
- playlist create *name*
  - Create playlist
- playlist delete *name*
  - Delete playlist
- pb!playlist play *name* or pb!music playlist *name*?
  - Start playlist

### PR DESCRIPTION
**Pull request by HGotthard**
## Requirements for Contributing

* [x] The changed and/or added Code should be documented and understandable.
* [x] The changed and/or added Code should follow the Code Conventions.

## Type of the Pull Request
* [ ] Bugfix
* [x] Feature change
* [ ] Documentation change
* [ ] Something different

## Description of the Changes

- Adds the new playlist commands to create, delete, play a playlist. 

Commands:
*playlist create <playlist name>* creates a new playlist.
*playlist queue <playlist name>* creates a new playlist from the current queue.
*playlist delete <playlist name>* deletes the playlist.
*playlist play <playlist name>* loads a previously saved playlist in the queue.
*playlist list* lists all your playlists.
*playlist add <playlist name>* adds a song to your playlist.
*playlist remove <playlist name>* removes a song from your playlist.
*playlist songs <playlist name>* lists all songs in your playlist.

## References

Resolves #81

### CODE REVIEW

**Review by byNoobiYT — APPROVED** [review]
Thanks for your contribution!

**Comment by ShowMeYourSkil** [comment]
Hi, 
my playlist does not save in my database.

**Comment by byNoobiYT** [comment]
Please file an issue to report the bug.

**Comment by ShowMeYourSkil** [comment]
Ok thank you! I <3 progen it is my favorite bot. Mee6 is buhh, Progen is jeaaaahhh

**Pull request merged**
